image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off
install:
  - chmod +x gradlew

build_script:
  - ./gradlew test -Dselenide.headless=true --info
after_build_script:
  - ./gradlew allureReport -Dselenide.headless=true --info
artifacts:
  paths:
    - build/reports/allure-report/allureReport/*

